Repository CS2103-AY1819S2-W11-3/main, pull requests merged in 2019-04, with the labels that each got.

#103 Add Rating and Year Charts
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/model/chart/Chart.java
  src/main/java/seedu/travel/ui/DisplayCard.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
  src/main/resources/view/DisplayListCard.fxml
  src/main/resources/view/LightTheme.css
Labels: priority.High, type.Enhancement

#105 Add ExpandedPlacePanel and command switching between ExpandedPlacePanel and DisplayListPanel
  docs/DeveloperGuide.adoc
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/logic/commands/SelectCommand.java
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
  src/main/java/seedu/travel/ui/ExpandedPlacePanel.java
  src/main/java/seedu/travel/ui/PlaceListPanel.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
  src/main/resources/view/ExpandedPlacePanel.fxml
  src/main/resources/view/RightParentPanel.fxml
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: priority.High

#110 Chart bug fixes and refactoring
  build.gradle
  src/main/java/seedu/travel/MainApp.java
  src/main/java/seedu/travel/model/ChartBook.java
  src/main/java/seedu/travel/model/Model.java
  src/main/java/seedu/travel/model/ModelManager.java
  src/main/java/seedu/travel/model/ReadOnlyCountryChart.java
  src/main/java/seedu/travel/model/ReadOnlyRatingChart.java
  src/main/java/seedu/travel/model/ReadOnlyYearChart.java
  src/main/java/seedu/travel/model/UserPrefs.java
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/model/chart/Chart.java
  src/main/java/seedu/travel/model/chart/CountryChart.java
  src/main/java/seedu/travel/model/chart/CountryChartList.java
  src/main/java/seedu/travel/model/chart/RatingChart.java
  src/main/java/seedu/travel/model/chart/RatingChartList.java
  src/main/java/seedu/travel/model/chart/YearChart.java
  src/main/java/seedu/travel/model/chart/YearChartList.java
  src/main/java/seedu/travel/model/chart/exceptions/CountryChartNotFoundException.java
  src/main/java/seedu/travel/model/chart/exceptions/RatingChartNotFoundException.java
  src/main/java/seedu/travel/model/chart/exceptions/YearChartNotFoundException.java
  src/main/java/seedu/travel/storage/ChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonTravelBuddyStorage.java
  src/main/java/seedu/travel/storage/Storage.java
  src/main/java/seedu/travel/storage/StorageManager.java
  src/main/java/seedu/travel/ui/CountryChartUi.java
  src/main/java/seedu/travel/ui/DisplayCard.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
  src/main/java/seedu/travel/ui/PlaceCard.java
  src/main/java/seedu/travel/ui/PlaceListPanel.java
  src/main/java/seedu/travel/ui/RatingChartUi.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
  src/main/java/seedu/travel/ui/YearChartUi.java
  src/main/resources/view/DisplayListPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/default.html
  src/test/java/seedu/travel/logic/LogicManagerTest.java
  src/test/java/seedu/travel/logic/commands/AddCommandTest.java
  src/test/java/seedu/travel/storage/StorageManagerTest.java
  src/test/java/seedu/travel/ui/MainWindowCloseTest.java
Labels: severity.Low, type.Bug

#114 Rename organization to all uppercase
  README.adoc
  build.gradle
Labels: severity.Low, type.Bug

#113 Add a Codacy badge to README.adoc
  README.adoc
Labels: priority.Medium

#117 Implement JUnit Testing for Chart feature
  README.adoc
  src/main/java/seedu/travel/model/ChartBook.java
  src/main/java/seedu/travel/model/chart/CountryChart.java
  src/main/java/seedu/travel/model/chart/CountryChartList.java
  src/main/java/seedu/travel/model/chart/RatingChart.java
  src/main/java/seedu/travel/model/chart/YearChart.java
  src/main/java/seedu/travel/storage/ChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/storage/StorageManager.java
  src/test/data/JsonChartBookStorageTest/invalidAndValidCountryChart.json
  src/test/data/JsonChartBookStorageTest/invalidAndValidRatingChart.json
  src/test/data/JsonChartBookStorageTest/invalidAndValidYearChart.json
  src/test/data/JsonChartBookStorageTest/invalidCountryChart.json
  src/test/data/JsonChartBookStorageTest/invalidRatingChart.json
  src/test/data/JsonChartBookStorageTest/invalidYearChart.json
  src/test/data/JsonChartBookStorageTest/notJsonFormat.json
  src/test/java/seedu/travel/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/travel/model/chart/CountryChartListTest.java
  src/test/java/seedu/travel/storage/JsonChartBookStorageTest.java
  src/test/java/seedu/travel/storage/StorageManagerTest.java
  src/test/java/seedu/travel/testutil/CountryChartBuilder.java
  src/test/java/seedu/travel/testutil/RatingChartBuilder.java
  src/test/java/seedu/travel/testutil/TypicalCountryChart.java
  src/test/java/seedu/travel/testutil/TypicalPlaces.java
  src/test/java/seedu/travel/testutil/TypicalRatingChart.java
  src/test/java/seedu/travel/testutil/TypicalYearChart.java
  src/test/java/seedu/travel/testutil/YearChartBuilder.java
Labels: priority.Medium, type.Task

#118 Fix RightParentPanel and null ExpandedPlacePanel bug
  src/main/java/seedu/travel/ui/ExpandedPlacePanel.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
Labels: priority.High, type.Bug

#119 Implement JUnit Testing for Chart feature
  src/test/java/seedu/travel/model/ChartBookTest.java
Labels: priority.Medium, type.Task

#121 Add functionality to display search query upon successful search
  docs/UserGuide.adoc
  docs/images/UIsearchcountryresults.png
  docs/images/UIsearchratingresults.png
  docs/images/UIsearchresults.png
  docs/images/UIsearchtagsresults.png
  docs/images/UIsearchyearresults.png
  docs/team/nivenang.adoc
  src/main/java/seedu/travel/logic/commands/SearchCommand.java
  src/main/java/seedu/travel/logic/commands/SearchCountryCommand.java
  src/main/java/seedu/travel/logic/commands/SearchRatingCommand.java
  src/main/java/seedu/travel/logic/commands/SearchTagsCommand.java
  src/main/java/seedu/travel/logic/commands/SearchYearCommand.java
  src/main/java/seedu/travel/logic/parser/SearchYearCommandParser.java
  src/main/java/seedu/travel/model/place/CountryCodeContainsKeywordsPredicate.java
  src/main/java/seedu/travel/model/place/NameContainsKeywordsPredicate.java
  src/main/java/seedu/travel/model/place/RatingContainsKeywordsPredicate.java
  src/main/java/seedu/travel/model/place/TagContainsKeywordsPredicate.java
  src/main/java/seedu/travel/model/place/YearContainsKeywordsPredicate.java
  src/test/java/seedu/travel/logic/commands/SearchCommandTest.java
  src/test/java/seedu/travel/logic/commands/SearchCountryCommandTest.java
  src/test/java/seedu/travel/logic/commands/SearchRatingCommandTest.java
  src/test/java/seedu/travel/logic/commands/SearchTagsCommandTest.java
  src/test/java/seedu/travel/logic/commands/SearchYearCommandTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SearchCountryCommandSystemTest.java
  src/test/java/systemtests/SearchRatingCommandSystemTest.java
  src/test/java/systemtests/SearchTagsCommandSystemTest.java
  src/test/java/systemtests/SearchYearCommandSystemTest.java
Labels: priority.Medium, type.Task

#122 Update Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.Medium

#123 Fixed unnecessary spaces in UG
  docs/UserGuide.adoc
Labels: type.Task

#124 Documentation housekeeping
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task

#135 Fix documentation errors found in PE dry run
  docs/UserGuide.adoc
  docs/images/clearCommand.png
  docs/team/nivenang.adoc
  src/main/java/seedu/travel/logic/commands/AddCommand.java
Labels: type.Bug

#164 Increase readability for bar chart
  docs/UserGuide.adoc
  src/main/java/seedu/travel/ui/DisplayCard.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
Labels: priority.High, severity.Low, type.Bug

#165 Modify User Guide
  docs/UserGuide.adoc
Labels: type.Task

#166 Update documentation for UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Chart_ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/Command_Generate_SequenceDiagram.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Chart_ModelClassBetterOopDiagram.png
  docs/images/GenerateCommandSeqDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/generateCommand7.png
  docs/images/generateCommand8.png
  docs/team/chung-ming.adoc
  src/main/java/seedu/travel/ui/ChartCard.java
  src/main/java/seedu/travel/ui/ChartListPanel.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
  src/main/resources/view/ChartListCard.fxml
  src/main/resources/view/ChartListPanel.fxml
Labels: type.Task

#170 Modify DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenerateCommandActivityDiagram.pptx
  docs/diagrams/SearchCommandActivityDiagram.pptx
  docs/images/GenerateCommandActivityDiagram.png
  docs/team/chung-ming.adoc
  src/main/java/seedu/travel/MainApp.java
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/ui/ChartCard.java
  src/main/java/seedu/travel/ui/ChartListPanel.java
  src/test/java/seedu/travel/logic/commands/GenerateCommandTest.java
Labels: type.Task

#171 Modify PPP and DG
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Chart_Combined.pptx
  docs/diagrams/Command_Generate_SequenceDiagram.pptx
  docs/diagrams/Generate_BeforeEditAfterEdit.pptx
  docs/diagrams/Generate_BeforeParamAfterParam.pptx
  docs/images/AddCommandSequenceDiagram.PNG
  docs/images/Chart_Combined.png
  docs/images/Chart_Country.png
  docs/images/Chart_ModelClassBetterOopDiagram.png
  docs/images/Chart_Rating.png
  docs/images/Chart_Year.png
  docs/images/GenerateCommandActivityDiagram.png
  docs/images/GenerateCommandSeqDiagram.png
  docs/images/Generate_BeforeEditAfterEdit.png
  docs/images/Generate_BeforeParamAfterParam.png
  docs/images/Generate_Clear.png
  docs/images/Generate_EditAfter.png
  docs/images/Generate_EditBefore.png
  docs/images/Generate_GenerateOnEmptyList.png
  docs/images/Generate_GenerateOnListNotEmpty.png
  docs/images/Generate_ListIsEmpty.png
  docs/images/Generate_ParameterBefore.png
  docs/images/Generate_Select1.png
  docs/images/Generate_Successful.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/chart1.png
  docs/images/generateCommand3.png
  docs/team/chung-ming.adoc
  docs/team/chung-ming.pdf
Labels: type.Task

#175 Update DATE_VISITED parameter in sample data and unit test case
  samplePlaces.txt
  src/test/java/seedu/travel/model/place/DateVisitedTest.java
Labels: type.Task

#179 Add JUnit tests for Photo feature and JsonChartBookStorageTest to improve coverage
  docs/images/2zHnFAN.jpg
  docs/images/3u6lq6r4477z.jpg
  docs/team/nivenang.adoc
  src/main/java/seedu/travel/logic/parser/ParserUtil.java
  src/test/data/JsonChartBookStorageTest/validCountryChart.json
  src/test/data/JsonChartBookStorageTest/validRatingChart.json
  src/test/data/JsonChartBookStorageTest/validYearChart.json
  src/test/java/seedu/travel/logic/commands/CommandTestUtil.java
  src/test/java/seedu/travel/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/travel/logic/parser/ParserUtilTest.java
  src/test/java/seedu/travel/storage/JsonChartBookStorageTest.java
  src/test/java/seedu/travel/testutil/PlaceBuilder.java
Labels: type.Testing

#181 Standardize asciidoc attributes and remove unused methods to increase coverage
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/chung-ming.adoc
  docs/team/chung-ming.pdf
  src/main/java/seedu/travel/storage/ChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/storage/StorageManager.java
Labels: type.Task, type.Testing

#183 Add tests for ChartBookStorage
  docs/team/chung-ming.adoc
  docs/team/chung-ming.pdf
  src/main/java/seedu/travel/storage/ChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/storage/Storage.java
  src/main/java/seedu/travel/storage/StorageManager.java
  src/test/java/seedu/travel/storage/JsonChartBookStorageTest.java
Labels: type.Testing

#189 Increase Test coverage for ExpandedPlacePanel, Place classes
  src/main/java/seedu/travel/model/place/Photo.java
  src/main/java/seedu/travel/ui/ExpandedPlacePanel.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
  src/test/java/seedu/travel/model/place/AddressTest.java
  src/test/java/seedu/travel/model/place/DescriptionTest.java
  src/test/java/seedu/travel/model/place/NameTest.java
  src/test/java/seedu/travel/model/place/PhotoTest.java
  src/test/java/seedu/travel/testutil/Assert.java
  src/test/java/seedu/travel/ui/ExpandedPlacePanelTest.java
Labels: type.Testing

#188 Modify UG, DG and PPP for Chart feature
  docs/CountryCodes.html
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/Chart_ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/Command_Generate_SequenceDiagram.pptx
  docs/images/Chart_ModelClassBetterOopDiagram.png
  docs/images/GenerateCommandSeqDiagram.png
  docs/team/chung-ming.adoc
  docs/team/chung-ming.pdf
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/storage/ChartBookStorage.java
  src/main/java/seedu/travel/storage/JsonChartBookStorage.java
  src/main/java/seedu/travel/ui/ChartCard.java
  src/test/java/seedu/travel/storage/JsonChartBookStorageTest.java
Labels: type.Task

#192 Add Non-Functional Requirements to DG
  docs/DeveloperGuide.adoc
  docs/team/chung-ming.adoc
  docs/team/chung-ming.pdf
Labels: type.Task

#195 Fix grammer issue in UG
  docs/UserGuide.adoc
Labels: type.Task

#199 Modify UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/diagrams/Chart_ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/Command_Generate_SequenceDiagram.pptx
  docs/diagrams/GenerateCommandActivityDiagram.pptx
  docs/diagrams/Generate_BeforeParamAfterParam.pptx
  docs/images/Chart_ModelClassBetterOopDiagram.png
  docs/images/GenerateCommandActivityDiagram.png
  docs/images/GenerateCommandSeqDiagram.png
  docs/images/Generate_BeforeParamAfterParam.png
  docs/images/Generate_ListIsEmpty.png
  docs/images/Generate_ParameterBefore.png
  docs/images/Generate_Select1.png
  docs/images/Generate_Successful.png
  docs/team/chung-ming.pdf
Labels: type.Task
