Repository CS2103-AY1819S2-W11-3/main, pull requests merged in 2019-03, with the labels that each got.

#60 Add generate command
  docs/UserGuide.adoc
  docs/team/chung-ming.adoc
  src/main/java/seedu/address/logic/commands/GenerateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium

#74 Modify Developer Guide
  docs/DeveloperGuide.adoc
Labels: type.Task

#84 Add Date Visited
  src/main/java/seedu/travel/logic/commands/EditCommand.java
  src/main/java/seedu/travel/logic/parser/AddCommandParser.java
  src/main/java/seedu/travel/logic/parser/CliSyntax.java
  src/main/java/seedu/travel/logic/parser/EditCommandParser.java
  src/main/java/seedu/travel/logic/parser/ParserUtil.java
  src/main/java/seedu/travel/model/chart/Chart.java
  src/main/java/seedu/travel/model/place/DateVisited.java
  src/main/java/seedu/travel/model/place/Place.java
  src/main/java/seedu/travel/model/util/SampleDataUtil.java
  src/main/java/seedu/travel/storage/JsonAdaptedPlace.java
  src/main/java/seedu/travel/ui/ChartUi.java
  src/main/java/seedu/travel/ui/PlaceCard.java
  src/main/resources/view/PlaceListCard.fxml
  src/test/data/JsonSerializableTravelBuddyTest/duplicatePlaceTravelBuddy.json
  src/test/data/JsonSerializableTravelBuddyTest/invalidPlaceTravelBuddy.json
  src/test/data/JsonSerializableTravelBuddyTest/typicalPlacesTravelBuddy.json
  src/test/data/JsonTravelBuddyStorageTest/invalidAndValidPlaceTravelBuddy.json
  src/test/data/JsonTravelBuddyStorageTest/invalidPlaceTravelBuddy.json
  src/test/java/seedu/travel/logic/LogicManagerTest.java
  src/test/java/seedu/travel/logic/commands/CommandTestUtil.java
  src/test/java/seedu/travel/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/travel/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/travel/model/place/CountryCodeTest.java
  src/test/java/seedu/travel/model/place/DateVisitedTest.java
  src/test/java/seedu/travel/storage/JsonAdaptedPlaceTest.java
  src/test/java/seedu/travel/storage/JsonSerializableTravelBuddyTest.java
  src/test/java/seedu/travel/testutil/EditPlaceDescriptorBuilder.java
  src/test/java/seedu/travel/testutil/PlaceBuilder.java
  src/test/java/seedu/travel/testutil/PlaceUtil.java
  src/test/java/seedu/travel/testutil/TypicalPlaces.java
  src/test/java/seedu/travel/ui/PlaceListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High

#82 Fix unable to edit only country code bug
  src/main/java/seedu/travel/logic/commands/EditCommand.java
Labels: type.Bug

#83 Implement Search Country feature
  src/main/java/seedu/travel/commons/util/StringUtil.java
  src/main/java/seedu/travel/logic/commands/SearchCountryCommand.java
  src/main/java/seedu/travel/logic/parser/SearchCountryCommandParser.java
  src/main/java/seedu/travel/logic/parser/SearchRatingCommandParser.java
  src/main/java/seedu/travel/logic/parser/SearchTagsCommandParser.java
  src/main/java/seedu/travel/logic/parser/TravelBuddyParser.java
  src/test/data/JsonSerializableTravelBuddyTest/typicalPlacesTravelBuddy.json
  src/test/java/seedu/travel/commons/util/StringUtilTest.java
  src/test/java/seedu/travel/logic/commands/CommandTestUtil.java
  src/test/java/seedu/travel/logic/commands/SearchCountryCommandTest.java
  src/test/java/seedu/travel/logic/parser/ParserUtilTest.java
  src/test/java/seedu/travel/logic/parser/SearchCountryCommandParserTest.java
  src/test/java/seedu/travel/logic/parser/SearchRatingCommandParserTest.java
  src/test/java/seedu/travel/logic/parser/TravelBuddyParserTest.java
  src/test/java/seedu/travel/model/place/CountryCodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/travel/model/place/RatingContainsKeywordsPredicateTest.java
  src/test/java/seedu/travel/testutil/TypicalPlaces.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SearchCountryCommandSystemTest.java
Labels: priority.High, type.Task

#85 Implement Search Year feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/travel/commons/util/StringUtil.java
  src/main/java/seedu/travel/logic/commands/SearchYearCommand.java
  src/main/java/seedu/travel/logic/parser/SearchYearCommandParser.java
  src/main/java/seedu/travel/logic/parser/TravelBuddyParser.java
  src/main/java/seedu/travel/model/place/DateVisited.java
  src/main/java/seedu/travel/model/place/YearContainsKeywordsPredicate.java
  src/test/java/seedu/travel/commons/util/StringUtilTest.java
  src/test/java/seedu/travel/logic/commands/SearchYearCommandTest.java
  src/test/java/seedu/travel/logic/parser/ParserUtilTest.java
  src/test/java/seedu/travel/logic/parser/SearchYearCommandParserTest.java
  src/test/java/seedu/travel/logic/parser/TravelBuddyParserTest.java
  src/test/java/seedu/travel/model/place/CountryCodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/travel/model/place/DateVisitedTest.java
  src/test/java/seedu/travel/model/place/YearContainsKeywordsPredicateTest.java
  src/test/java/seedu/travel/testutil/TypicalPlaces.java
  src/test/java/systemtests/SearchYearCommandSystemTest.java
Labels: priority.High, type.Task

#87 Update Java version in PlaceListCard from 8 to 11
  src/main/resources/view/PlaceListCard.fxml
Labels: type.Bug

#88 Modify UI
  build.gradle
  docs/UserGuide.adoc
  docs/team/PremBagda.adoc
  docs/team/chung-ming.adoc
  docs/team/nivenang.adoc
  docs/team/shaungohsc.adoc
  src/main/java/seedu/travel/commons/core/GuiSettings.java
  src/main/java/seedu/travel/logic/commands/AddCommand.java
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/model/Model.java
  src/main/java/seedu/travel/model/ModelManager.java
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/model/chart/Chart.java
  src/main/java/seedu/travel/model/util/SampleDataUtil.java
  src/main/java/seedu/travel/ui/ChartUi.java
  src/main/java/seedu/travel/ui/UiManager.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PlaceListCard.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/travel/TestApp.java
  src/test/java/seedu/travel/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#93 Add Chart Feature
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/model/Model.java
  src/main/java/seedu/travel/model/ModelManager.java
  src/main/java/seedu/travel/model/VersionedTravelBuddy.java
  src/main/java/seedu/travel/model/chart/Chart.java
  src/main/java/seedu/travel/model/place/DateVisited.java
  src/main/java/seedu/travel/model/place/YearContainsKeywordsPredicate.java
  src/main/java/seedu/travel/storage/JsonAdaptedPlace.java
  src/main/java/seedu/travel/ui/CountryChartUi.java
  src/main/java/seedu/travel/ui/DisplayCard.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
  src/main/java/seedu/travel/ui/MainWindow.java
  src/main/java/seedu/travel/ui/PlaceCard.java
  src/main/java/seedu/travel/ui/RatingChartUi.java
  src/main/java/seedu/travel/ui/UiManager.java
  src/main/java/seedu/travel/ui/YearChartUi.java
  src/main/resources/view/DisplayListCard.fxml
  src/main/resources/view/DisplayListPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/travel/TestApp.java
  src/test/java/seedu/travel/logic/commands/AddCommandTest.java
  src/test/java/seedu/travel/testutil/PlaceUtil.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/TravelBuddySystemTest.java
Labels: priority.High, type.Epic

#102 Add RightParentPanel class
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/travel/logic/Logic.java
  src/main/java/seedu/travel/logic/LogicManager.java
  src/main/java/seedu/travel/logic/commands/GenerateCommand.java
  src/main/java/seedu/travel/logic/commands/SelectCommand.java
  src/main/java/seedu/travel/model/Model.java
  src/main/java/seedu/travel/model/ModelManager.java
  src/main/java/seedu/travel/ui/BrowserPanel.java
  src/main/java/seedu/travel/ui/DisplayListPanel.java
  src/main/java/seedu/travel/ui/ExpandedPlacePanel.java
  src/main/java/seedu/travel/ui/MainWindow.java
  src/main/java/seedu/travel/ui/PlaceListPanel.java
  src/main/java/seedu/travel/ui/RightParentPanel.java
  src/main/resources/view/ExpandedPlacePanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RightParentPanel.fxml
  src/test/java/seedu/travel/logic/commands/AddCommandTest.java
  src/test/java/seedu/travel/ui/PlaceListPanelTest.java
Labels: priority.High, type.Epic
